# Generated by Django 5.1.3 on 2024-11-23 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend_api', '0006_alter_iotfillingcontainer_time_of_detect'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='containers',
            name='fill_level',
        ),
        migrations.AlterField(
            model_name='containers',
            name='last_updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
