# Generated by Django 5.1.3 on 2024-12-01 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend_api', '0008_alter_stationofcontainers_last_reserved'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stationofcontainers',
            name='station_of_containers_name',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
