# Generated by Django 5.1.3 on 2024-11-22 18:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend_api', '0003_containers_notificationtypes_stationofcontainers_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='stationofcontainers',
            old_name='name',
            new_name='station_of_containers_name',
        ),
    ]
